# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=31)),
                ('first_name', models.CharField(max_length=31)),
                ('state', models.CharField(max_length=2)),
                ('twitter_id', models.CharField(max_length=31)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
