# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('republicans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Senator',
            new_name='Republican',
        ),
        migrations.DeleteModel(
            name='Governor',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
