# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('republicans', '0003_republican_gov_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republican',
            name='gov_type',
            field=models.CharField(choices=[(b'Sen', b'Senator'), (b'Rep', b'Representative'), (b'Gov', b'Governor')], default=b'Rep', max_length=3),
        ),
    ]
