# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('republicans', '0005_auto_20160731_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='republican',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 8, 1, 2, 31, 53, 800557, tzinfo=utc), max_length=31, unique=True),
            preserve_default=False,
        ),
    ]
